### ISSUE TITLE
Enable CLA hook for PRs

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#11]
In devon4j PRs do not have the CLA check hook. I have no clue how to set this up.

**Comment by soyrochus** [comment]
@Jorge-Dacal  will take care of this AND documement the process if not already documented

**Comment by Jorge-Dacal** [comment]
Hi @hohwille,

I have tried to log into the [cla website](https://cla-assistant.io/) with our devonfw-core account to manage our CLAs but I do not know why I can not enter with devonfw-core but I can enter to the the website with other GitHub accounts.

I need to log in with devonfw-core to add the CLA in our repositories, because of that I opened an [issue](https://github.com/cla-assistant/cla-assistant/issues/378). I am waiting for their response and also going to try to log in every so often.

I will keep you informed.

**Comment by hohwille** [comment]
@Jorge-Dacal awesome. I already tested it with my new PR and it is working fine.
Thank you so much :+1:
