### ISSUE TITLE
Wiki: Link to Database Options is broken

### ISSUE THREAD

**Issue by phschimm** [devonfw/devon4j#269]
The link under `Options > Databases` in the sidebar leads to a 404-page. It's supposed to link to:
https://github.com/devonfw/devonfw-guide/blob/master/general/db/guide-database.asciidoc

**EDIT:**
Actually not such an easy fix since (according to [.travis.yml](https://github.com/devonfw/devon4j/blob/develop/.travis.yml)) every `.asciidoc` extension gets removed while cloning to the `.wiki` repo. This is fine for relative links to files in the `documentation` directroy, but breaks external links. :confused: 
I wonder why such a complicated config is still used for this simple process. There's a "[Publish to GitHub Wiki](https://github.com/marketplace/actions/publish-to-github-wiki)" action, that could simplify this process massively.

**Comment by hohwille** [comment]
@phschimm thanks for reporting this. Also thanks for your suggestions to improve and simplify.
IMHO the actual complexity and problems come from github itself as it renders AsciiDoc or Markup in generally totally inconsistent and different in each context (issue/PR comments, markup files in git repos, wiki pages, etc.). So while in one place the `.asiidoc` extension is required and in the other place it must not be present.
It is not that we want this to be complex - it is only that we want to have it working.

If the suggested "Publish to GitHub Wiki" action can really solve all these problems, I am very happy to replace our custom process with it. Have you already tested it (e.g. by forking this repo and configuring that github action for your fork)?

**Comment by phschimm** [comment]
I wanted to test this and already ran into an inherent problem with the GitHub Actions system:

If you just use an action from the marketplace and its creator changes something, your whole pipeline could very well break ... This just happened to one of my personal repos using the "[Publish to GitHub Wiki](https://github.com/marketplace/actions/publish-to-github-wiki)" action. :unamused:

So it's probably better to have some quirks but full control, instead of quirks and no control. :sweat_smile:

**Comment by hohwille** [comment]
The problem comes from this simple command that is copy&pasted to all repos:
https://github.com/devonfw/devon4j/blob/c03f577955d9e0cd98943db2687306b43b07df3d/.travis.yml#L41

Ideally we should have a `tool` like `docgen` that is used by our CI pipeline so we do not have to update all our `.travis.yml` files if thinks like this have to change.

**Comment by sjimenez77** [comment]
The database content is clearly a cross content and was correctly moved to the general section of the guide and included in its own section **Choose your Database**. The link we are talking about is in the sidebar of this wiki and therefore **it does not appear in the PDF nor the website**. So, why not do we just use the website link in the sidebar for this kind of links that point to asciidocs outside the current wiki and then we can plan a discussion to study the alternatives we have to improve this process?

**Comment by hohwille** [comment]
For me both ways are fine:
1. fix the processing (removal of `.asciidoc` extension) in `.travis.yml` of this repo
2. remove `_sidebar.asciidoc` from documentation and instead only maintain it in the wiki directly

However, we have to fix 1. anyways as there are other such extenal links and we never understood before why those sometimes are broken in the wikis. So if we can quickly fix via 1. we should go for that. Otherwise do 2. as an intermediate fix, please.

**Comment by ssarmokadam** [comment]
Can close this issue and we need to create new issue in devonfw documentation related to travis.
