### ISSUE TITLE
Issue in running executable jar 

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/devon4j#295]
### Expected behavior

As a user , I want to start newly created application using bootified jar with command java -jar jarname.

### Actual behavior

When executed this command it gives error "no main manifest attribute"

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Create new devon4j application.
2. In  core module\target folder launch jar file with command java -jar jarfilename

### Affected version:

* OS: Windows

**Comment by ssarmokadam** [comment]
Right way to test it is to run bootified war from server module. So this is an invalid issue.

**Comment by hohwille** [comment]
Maybe we can take this issue as an opportunity to improve our documentation.
My suggested place would be to add a section here:
https://github.com/devonfw/devon4j/blob/develop/documentation/tutorial-newapp.asciidoc
Also feel free to add a small section `make jar not war` explaining how to change `server/pom.xml` such that a bootified war is created instead of bootified war for the `server` module.
