### ISSUE TITLE
Fix CSRF protection support

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/devon4j#307]
### Description

Current devon4ng application implements a method to retrieve CSRF token from the backend:

```TypeScript
  getCsrf(): string {
    return this.serverPath + 'security/v1/csrftoken';
  }
```
From [this file](https://github.com/devonfw/devon4ng-application-template/blob/develop/src/app/core/shared/business-operations.service.ts#L17).

UPDATE: new URL path is `csrf/v1/token`.

This worked like a charm months ago. But it seems the 24th of April, this service `csrftoken` was completely removed from devon4j. I think the related PR is #244 

As I can see in [this file](https://github.com/devonfw/devon4j/blob/9fcfd8f48ca229578214c358678743f327c93e55/templates/server/src/main/resources/archetype-resources/api/src/main/java/__packageInPathFormat__/general/service/api/rest/SecurityRestService.java), the service was defined:

```Java
  @GET
  @Path("/csrftoken/")
  CsrfToken getCsrfToken(@Context HttpServletRequest request, @Context HttpServletResponse response);
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Download https://github.com/devonfw/devon4ng-application-template/
2. Set environment.ts file to use `csrf`
3. Try to login and you will face 404, statusText: "OK", url: "http://localhost:8081/services/rest/security/v1/csrftoken 

### Comments/Hints:

Has devon4j completely disabled CSRF support? Do we have now to use JWT for the front-end?

**Comment by hohwille** [comment]
First of all we have to clarify what the actual bug is here.
IMHO you are talking about the `SecurityRestService`:
https://github.com/devonfw/devon4j/blob/4e00cf2d746b1038afcc65d0830bc3ba09c4f213/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/rest/SecurityRestServiceImpl.java

This has been removed from our app template.
However, IMHO this is NOT a bug but has been done on purpose as people demanded to app template to be minimalistic and they want `opt-in` rather than `opt-out`.
So first we have to clarify directions before doing any change.
I can not find the commit that deleted this `SecurityRestServiceImpl` but I assume it is related to issue #171.

What confuses me also is that we have removed this service but still have `CSRF` enabled by default:
https://github.com/devonfw/devon4j/blob/867351c613986c09594c382fceff02196437b87b/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/BaseWebSecurityConfig.java#L79
and also include other "clutter" regarding it like
https://github.com/devonfw/devon4j/blob/9b8f9461997bb5d8048a9fec42bec3625652eec3/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/security/CsrfRequestMatcher.java
and
https://github.com/devonfw/devon4j/blob/9b8f9461997bb5d8048a9fec42bec3625652eec3/templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/common/impl/config/CsrfTokenImpl.java

So we need a clear raodmap here:
1. reintroduce `SecurityRestService` including its implementation, test, etc. back into the template (IMHO not recommended)
2. create a devon4j module for CSRF support and move all the stuff there and further reduce the app template (archetype). Even consider to create a CSRF autostarter for spring-boot that will try to automagtically integrate CSRF protection and service automatically. Then add documentation how to use this. Easiest case would be to add `devon4j-starter-csrf` as dependency and you are done. For those who want more control they can copy the service from the module to their project and customizer to their needs if the autostarter is insufficinet for whatever reason.

I would strongly suggest to go for option 2.

**Comment by jdiazgon** [comment]
Option 2 is fine for me too. Thanks!

**Comment by hohwille** [comment]
Done with PR #307
