### ISSUE TITLE
Authentication / Authorization Links broken

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon4j#319]
### Expected behavior

As a user of devon4j, I want to read more about Authentication/Authorization so that I can evaluate devon4j for my purpose.

### Actual behavior

Going to https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-access-control.asciidoc the links to Authentication and Authorization are broken.

**Comment by hohwille** [comment]
@maybeec thanks for letting us know about this problem.
However, these links are properly working on the source:
https://github.com/devonfw/devon4j/blob/develop/documentation/guide-access-control.asciidoc#access-control

We really need to file and *fix* bugs in docgen and especially in the website generation. We have problems like these since ages and do not seem to be able to properly fix them. From `devon4j` this is not an issue: We are providing documentation as Asciidoc and it works on github as well as in our PDF document. Therefore the website generation has to be fixed. If there is a workaround to fix it in the website without breaking it on github and in our PDF we are happy to receive a PR.

**Comment by maybeec** [comment]
Thanks for clarificiation. Do you actually have a ticket for that on docgen?
If so @ssarmokadam, please create a ticket in addition for that in the backlog of the core team, so we can focus on this with high prio!

**Comment by hohwille** [comment]
As always we should first do a simple analysis to see what is actually wrong in the website:
The proper link should be:
```
https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-access-control.asciidoc_authentication
```
However the actual link that gets rendered is:
```
https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-access-control.asciidoc_guide-access-control.asciidoc_Authentication
```
As you can see the actual link contains `guide-access-control.asciidoc` twice in the anchor.

This is IMHO neither a bug in devon4j nor in docgen. It comes from the plugin we are using in the website generation that is IMHO rather unsupported and that I never entirely understood. It makes some decisions to join multiple AsciiDoc files into one HTML document or split them according to the level of the TOC. How could docgen know this? How could docgen at all know that the website is currently generated using this strange plugin and it should do some quirks as workaround.

IMHO we need to establish a true expert in core-team to take over the codebase of this plugin for the website generation and fix such bugs or we should actually find a totally new approach and get rid of this unsupported plugin at all.

**Comment by ssarmokadam** [comment]
@hohwille  created issue on JIRA P002116-1436

**Comment by hohwille** [comment]
Thanks @ssarmokadam - I am therefore closing this github issue.
