### ISSUE TITLE
devon4j-doc build is failing in windows os

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devon4j#358]
Build is failing due to the below badge reference 

https://img.shields.io/maven-central/v/com.devonfw.java.templates/devon4j-template-server.svg?label=Maven%20Central

in tutorial-newapp.asciidoc .

**Comment by hohwille** [comment]
The problem is a bug in asciidoctor that wants to create a file for the image from the URL and windows prevents to have a query (the part after questionmark in URL) in a local filename.
Suggested fix is to use the JavaDoc badge instead of the maven one:
```
image:https://javadoc.io/badge2/com.devonfw.java.modules/devon4j-basic/javadoc.svg
```
Can you please test this? In case you provide a PR can you then also remove the "strip the leading v from the version" part from the documentation as the JavaDoc badge does not prepend a `v` prefix.
