### ISSUE TITLE
Move Exception handling to General section

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/devon4j#449]
Validate if current exception handling document can be followed for Quarkus as well or any further changes required in it. If it is common for both move it to general section else add Exception Handling for devon4j and Quarkus in respective sections.

**Comment by hohwille** [comment]
The documentation is not spring specific in any way:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-exceptions.asciidoc

However, it is specific for the requirement of i18n and requires the usage of `mmm-util-nls`.
As we are changing towards less framework and minimized dependencies as well as opt-in rather than opt-out, we should instead consider to strip all these `mmm` dependencies and put a minimal exception base-class into our app template that has no external dependencies.
BTW: If someone wants to use such library, he should consider using `io.github.m-m-m:mmm-base` instead. It is improved and much more lightweight. Then you can add `io.github.m-m-m:mmm-nls` on top to add I18N/L10N.

**Comment by hohwille** [comment]
I created #562 and hence close this issue.

**Comment by hohwille** [comment]
> If it is common for both move it to general section else ...
This has always been the case:
https://github.com/devonfw/devon4j/blob/master/documentation/devon4j.asciidoc
