### ISSUE TITLE
How can i avoid reiteration of code mapping to eto from entity?

### ISSUE THREAD

**Issue by trivesc** [devonfw/devon4j#54]
In the new versions of the structure of devon4j i have been having issues with code reiteration caused by not being able to create a save(Entity). Creating this method is not possible because the entities are generated in the core project and not in the api project. This fact forces me to transform to `ETO` to call a save method that will later transform to `ENTITY` with bean mapper. Example: 

I want to decrease the queue customers by one when deleting an accesscode. This is located in `UseCaseManageAccessCodeImpl`.

``` Java
	@Override
	public Boolean deleteAccessCode(long accessCodeId) {

		AccessCodeEntity accessCodeEntity = getAccessCodeRepository().find(accessCodeId);
		// Forced to map to ETO because I can't use entity in my QueueManagement
		QueueEto queueEto = getBeanMapper().map(accessCodeEntity.getQueue(),QueueEto.class);
		queueEto.setCustomers(queueEto.getCustomers() -1);
		getQueuemanagement().saveQueue(queueEto);

		LOG.debug("The queue with id '{}' has decreased its customers to: {}.", queueEto.getId(),
				queueEto.getCustomers());

		// we delete the accesscode
		getAccessCodeRepository().delete(accessCodeEntity);
		LOG.debug("The accesscode with id '{}' has been deleted.", accessCodeId);

		return true;
	}
```
This is the `saveQueue(QueueEto queue)` located in the `UseCaseManageQueueImpl`

``` Java
	@Override
	public QueueEto saveQueue(QueueEto queue) {

		Objects.requireNonNull(queue, "queue");

		// Transformation from QueueEto to QueueEntity
		QueueEntity queueEntity = getBeanMapper().map(queue, QueueEntity.class);

		// initialize, validate queueEntity here if necessary
		QueueEntity resultEntity = getQueueRepository().save(queueEntity);
		LOG.debug("Queue with id '{}' has been created.", resultEntity.getId());
		return getBeanMapper().map(resultEntity, QueueEto.class);
	}
```
If i try to make a new method in the `UseCaseManageQueue` interface to later implement it:
```Java
	QueueEto saveQueue(QueueEntity queue);
```
the `QueueEntity` can not be found because the `UseCaseManageQueue` is in the api and the `QueueEntity` is in the core. This is feasible in the previous structure (Devon dist 2.4.0) because both the interface and the implementation were in the core. Using my-thai-star:

In the `Dishmanagement`:
``` Java
...
  DishEto saveDish(DishEto dish);
  /**
   * Saves a dish and store it in the database.
   *
   * @param dish the {@link DishEntity} to create.
   * @return the new {@link DishEto} that has been saved with ID and version.
   */

  DishEntity saveDish(DishEntity dish) ;
....
```
In the `DishmanagementImpl`
``` Java
....
  @Override
  public DishEntity saveDish(DishEntity dish) {

    Objects.requireNonNull(dish, "dish");
    // initialize, validate dishEntity here if necessary
    DishEntity resultEntity = getDishDao().save(dish);
    LOG.debug("Dish with id '{}' has been created.", resultEntity.getId());

    return resultEntity ;
  }
....
```
Doing it in this way, we are going to avoid two mappings. One to transform from `ENTITY` to `ETO` to use the save and then, inside the save from `ETO` to `ENTITY`. If there is a way to do this in the previous structure i would like to see if there is a way to do it in the new one.

**Comment by maybeec** [comment]
Basically it's up to your architecture. If you need to pass data just for saving between components (communication using Eto's is required) without any additional business logic on save, Is it really the right cut of the datamodel to regarding components?
I am unsure about the Uc interfaces as if you mean they are in -api project, I am not sure why this should be the case.

**Comment by hohwille** [comment]
First of all it was always a design of oasp4j/devon4j that entities (as JPA managed objects) are part of the data-acsess layer and shall not be exposed out of the logic layer API to upper layers due to data-sourvegency reasons (you will end up in a mess if you do call by refenrence on JPA managed objects).

You can still have internal methods within the logic layer of the same component to reuse some logic directly on any entity. However, you may not expose this as API in the use-case interface.
Therefore the signiture `saveDish(DishEntity dish)` or `saveQueue(QueueEntity queue)` is wrong in the logic API. IMHO you simply do not need to expose it in the API and you are fine. Otherwise if you have to call it between components simply use TOs/ETOs instead of Entities. You do not need to worry too much about performance as the hibernate first level cache will prevent loding the same entity from being loaded multiple times from the DB in the same TX. Of course you may need to consider the whole thing that is going on and you can also have internal use-cases that directly work on entities if e.g. additonal bean mapping is a performance problem in your use-case scenario...

**Comment by hohwille** [comment]
I assume the question has been asked. Therefore I am closing this. If possible join us on Yammer, Teams, or any other open channel for discussions and prefer the github issue tracker rather for bugs, fixes, concrete feature requestes, or any kind of issue that implies changes to the codebase.
