### ISSUE TITLE
Batch template cannot be started

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon4j#67]
It seems, that the existing batch configuration served by the archetype is not working at all. First there is an exception as it tries to create a security bean although global method security is disabled.
Enabling it (why is it disabled?), you get an exception, that jobRegistry Bean is not provided.

I am using oasp 3.0.0, but I did not detect any difference in the latest template.

Also there seem to be EndpointAutoCofiguration excluded, but JmxAutoConfiguration not, which is not working either.

Just remembered, meanwhile I upgraded to latest SpringBoot Release. So maybe these issues are also as of this upgrade. Anyhow, maybe a good chance to check again.

**Comment by hohwille** [comment]
@maybeec can you give us some more hints to reproduce the problem?
We do have automated tests of the archetype including the batch option.
So does your error occur only when you start the spring boot app for the batch manually?
Otherwise if this is only related to your project using a more recent spring-boot version this issue will be considered as invalid but we can join forces to create version `3.1.0` such that it suits your needs.

**Comment by maihacke** [comment]
Could you please show here how exactly did you try to start the batch?

**Comment by maybeec** [comment]
This was referring to oasp4j 3.0.0, maybe this has been resolved already. Anyhow, I was generating the batch application by the archetype and starting the batch generated spring boot application without any success.

**Comment by maihacke** [comment]
Did you try this from eclipse or via cli?
At least for me it looks like our documentation is broken. The examples for starting the batches cannot work in opinion - at least the classpath is missing...

**Comment by maybeec** [comment]
I just tried by eclipse, `SpringBootApp -> Run as Java` these times.

**Comment by hohwille** [comment]
With the merged PR it is possible to start the batch from the template/archetype.
I close this issue. If you still have issues with batch, create a new concrete issue.
