### ISSUE TITLE
Migrate to newest version of dozer

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon4j#72]
The development of dozer has been restarted.
If we are not going for other mapping tools by default, we should at least migrate to the latest version of dozer fixing multiple often occurring issues in bigger projects.

https://github.com/DozerMapper/dozer

**Comment by hohwille** [comment]
@AbhayChandel please comment the current status. If done then also assign milestone and close.

**Comment by hohwille** [comment]
I got the response via mail:

> Dozer is not managed by Spring boot. Hence we need to update it at our end explicitly.
> In devon4j this is being managed using devon4j-bom and the current version is 5.5.1.
> Not sure if it will be straightforward to upgrade to the latest version 6.4.1, since it is different project then what it was back in 2014.
> I suggest, we can take up the migration and if the PR is stable enough then we can include it in 3.1.0.

Agreed. Lets start with PR.

**Comment by hohwille** [comment]
Thanks to @Rohit90700 this is fixed via PR #86

**Comment by hohwille** [comment]
I always thought we never made our fundamental features work with orika.
However, I just saw that we did since long:
* https://github.com/devonfw/devon4j/blob/develop/modules/beanmapping/src/main/java/com/devonfw/module/beanmapping/common/impl/orika/CustomMapperEto.java
* https://github.com/devonfw/devon4j/blob/develop/modules/beanmapping/src/test/java/com/devonfw/module/beanmapping/common/impl/orika/BeanMapperImplOrikaTest.java

So if we are planning an incompatible change for beanmapping anyhow with `3.2.0` why dont we go and switch to orika officially? Aint this about time?
* https://www.baeldung.com/java-performance-mapping-frameworks
* https://github.com/oasp/oasp4j/issues/4

**Comment by maybeec** [comment]
just read https://www.baeldung.com/java-performance-mapping-frameworks, I think it might be interesting to think about MapStruct as the default in the meantime.

**Comment by hohwille** [comment]
@maybeec MapStruct is not a drop-in replacement. It is a code-generater and can not serve with a generic API to map arbitrary objects. IMHO the philosophy is so different that it is not really to be considered for our existing BeanMapper API.
See https://github.com/oasp/oasp4j/issues/4

**Comment by hohwille** [comment]
I created issue #147 for this and therefore close this issue as it has already been done as planned initially.

**Comment by hohwille** [comment]
For the record:
https://github.com/devonfw/devon4j/commit/cadadf5f3191d8af36663d42c592296ce5afb8f6
This change will be released with `2020.04.002`.
