### ISSUE TITLE
Support 2-Factor Authentication

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#78]
It would be great to have support for 2-factor auth in devonfw:
* a working example in my-thai-star (e.g. as feature to enable per user or required for admins to avoid overcomplication of the sample app): https://github.com/devonfw/my-thai-star/
* a security module for devon4j (e.g. like https://github.com/devonfw/devon4j/pull/76)
* some documentation with guidance how to integrate and use the feature into your own app (https://github.com/devonfw-wiki/devon4j/wiki/guide-access-control - however ideally as a new page linked from there)

Just got in touch with Malte V. and Oliver H. - so if all goes right, Malte will do this as his bachelor thesis.

**Comment by hohwille** [comment]
Candidates for 2FA would be
* TOTP
* U2F

**Comment by markusschuh** [comment]
The so far already realised here TOTP support is great!

Nevertheless, for practical use inside production 2FA needs some additional user management features realised. I'm unsure, if those are already in scope of the 2FA or should be / were already mentioned as another feature request.
Since those are related to 2FA, I add this comment here:

_Credential reset_: Even a password can be lost - but it is even more likely for a 2FA that it stops working. (local OTP app broken / device lost / time sync issues / ... ) So some form of a _reset_ of  the access is even far more important, when 2FA is offered as login option. In a first draft this may just been guidance for a server admin, how to reset the TOTP. But at the end, some form of self service is needed. 

Such a reset could be realised for example via
- a button that sends an e-mail and activates the reset, when the included link is clicked in the next n hours.
- allow several credentials - potentially of different form factor - for a single user. If one access type is lost, another one could be used, to create a new one.
- a list of fixed strings as reset tokens. A specialised variant of last topic. Those tokens were accepted, but force an e-mail and require a new 2FA to be configured, before application access is granted again.

In the currently realised implementation the tech-savvy could of course take a photo of the QR - or just write down the secret from the text only display alternative. This secret is enough to generate a valid TOTP with help of another instance of some OTP app.
But this is no valid solution for some _Credential Reset_ as a service inside the application since it undermines the security strength, TOTP adds over fixed password authentication.

By the way, this detail is the reason, why TOTP on its own, is no 2FA. TOTP just is a 2nd factor, that could be added, e.g to a fixed password.
