### ISSUE TITLE
 Authorization of batches

### ISSUE THREAD

**Issue by vapadwal** [devonfw/devon4j#90]
Batch still needs to be started with the context of a user (e.g. our envers auditing will require a user to be logged in and that could be triggered from a batch). 

Please refer PR -https://github.com/devonfw/devon4j/pull/89

**Comment by maihacke** [comment]
I implemented an example which demonstrates how to do authentication: 
https://github.com/maihacke/my-thai-star/pull/1

The solution is quite simple.
1. Provide username and password as command line arguments
2. the batch includes a tasklet steps which internally creates a usernamepasswordauthentication for theses values
3. spring security does the normal authentication. This is quite similar to what https://github.com/devonfw/devon4j/blob/develop/modules/security/src/main/java/com/devonfw/module/security/common/impl/rest/JsonUsernamePasswordAuthenticationFilter.java does.

How would we include this into devonfw.
We could try do implement tasklets which does authentication out of the box, but for that we have to make many assumptions how the authentication for the user works.

My proposal would be to just document how to do it. In the end thats less than 20 lines of codes.

What do you think @hohwille , @vapadwal ?

**Comment by hohwille** [comment]
> My proposal would be to just document how to do it. In the end thats less than 20 lines of codes.

Perfect for me. Further in some cases the batch may not be able to verify any credentials (e.g. if project uses SPNEGO there is no password). If I have physical access to the machine where I start the batch, why would I need a password on the commandline? However, where does the batch get the permissions (grantedAuthorities) from? That would need to come from IAM somehow. So I am happy to read your documentation proposal as I am also not entirely clear what is the best practice in all situations. Anyhow I think a batch needs to do some kind of login to populate the authentication to spring security so that auditing (envers), authorization, etc. is working.

**Comment by hohwille** [comment]
PR #215 is merged. Should we close this issue or is there anything we need to improve?

* we have an example in MTSJ
* we have a documentation describing the problem and how to address it
* we can not provide a OOTB solution applicable to all projects and demands

Hence, I am closing this issue. PRs with improvements are always welcome.
